### ISSUE TITLE
Elmoin Meetup October 2017

### ISSUE THREAD

**Issue by pierrebeitz** [elmoin/elmoin-meetups#11]
**Date:** 24.10. / 26.10.

**Time:** 18:30

**Location:** Asked PhraseApp to have us again.

**Google Map**: 

**TODOS**:

  * [ ] Ideas for mobbing
  * [ ] Venue
  * [ ] Date / Time
  * [ ] Food / Snacks
  * [x] Prepare meetup event
  * [ ] Announce meetup event
  * [ ] Twitter announcement
